version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
    image: ${DOCKERHUB_USERNAME}/kimiyomi-frontend:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app

  app:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile
    image: ${DOCKERHUB_USERNAME}/kimiyomi-backend:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: